// Major Polish cities for autocomplete
export const polishCities = [
  'Warszawa',
  'Kraków',
  'Łódź',
  'Wrocław',
  'Poznań',
  'Gdańsk',
  'Szczecin',
  'Bydgoszcz',
  'Lublin',
  'Białystok',
  'Katowice',
  'Gdynia',
  'Częstochowa',
  'Radom',
  'Sosnowiec',
  'Toruń',
  'Kielce',
  'Gliwice',
  'Zabrze',
  'Bytom',
  'Olsztyn',
  'Rzeszów',
  'Ruda Śląska',
  'Rybnik',
  'Tychy',
  'Dąbrowa Górnicza',
  'Płock',
  'Elbląg',
  'Opole',
  'Gorzów Wielkopolski',
  'Włocławek',
  'Zielona Góra',
  'Tarnów',
  'Chorzów',
  'Kalisz',
  'Koszalin',
  'Legnica',
  'Grudziądz',
  'Słupsk',
  'Jaworzno',
  'Jastrzębie-Zdrój',
  'Jelenia Góra',
  'Nowy Sącz',
  'Jaworzno',
  'Konin',
  'Piotrków Trybunalski',
  'Lubin',
  'Inowrocław',
  'Ostrowiec Świętokrzyski',
  'Stargard',
  'Mysłowice',
  'Pabianice',
  'Gniezno',
  'Oława',
  'Głogów',
  'Chełm',
  'Zamość',
  'Tomaszów Mazowiecki',
  'Przemyśl',
  'Stalowa Wola',
  'Mielec',
  'Łomża',
  'Żywiec',
  'Tarnowskie Góry',
  'Kędzierzyn-Koźle',
  'Racibórz',
  'Świętochłowice',
  'Ostrołęka',
  'Siedlce',
  'Mysłowice',
  'Piła',
  'Ostrowiec Świętokrzyski',
  'Głogów',
  'Stargard',
  'Skierniewice',
  'Skarżysko-Kamienna',
  'Starachowice',
  'Zawiercie',
  'Tarnobrzeg',
  'Puławy',
  'Kraśnik',
  'Dębica',
  'Przemyśl',
  'Stalowa Wola',
  'Mielec',
  'Łomża',
  'Żywiec',
  'Tarnowskie Góry',
  'Kędzierzyn-Koźle',
  'Racibórz',
  'Świętochłowice',
  'Ostrołęka',
  'Siedlce',
  'Mysłowice',
  'Piła',
  'Ostrowiec Świętokrzyski',
  'Głogów',
  'Stargard',
  'Skierniewice',
  'Skarżysko-Kamienna',
  'Starachowice',
  'Zawiercie',
  'Tarnobrzeg',
  'Puławy',
  'Kraśnik',
  'Dębica',
];

// Function to filter cities based on input
export const filterCities = (input: string): string[] => {
  if (!input) return polishCities.slice(0, 10); // Show first 10 cities when no input

  return polishCities
    .filter((city) => city.toLowerCase().includes(input.toLowerCase()))
    .slice(0, 10); // Limit to 10 results
};
